language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
services:
  - mysql
  - postgresql
addons:
  postgresql: "9.5"
env:
  - DATABASE=sqlite
  - DATABASE=mysql
  - DATABASE=postgresql
gemfile:
  - gemfiles/rails60.gemfile
  - gemfiles/rails61.gemfile
before_script:
  - cd spec/dummy
  - bundle exec rake db:create db:migrate db:seed RAILS_ENV=test
  - cd ../..
script:
  - bundle exec rspec
