default: &default
  adapter: postgresql
  pool: 10
  timeout: 5000

development:
  <<: *default
  database: ar_scoping_with_assoc_development

test:
  <<: *default
  database: ar_scoping_with_assoc_test
  host: localhost
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: ar_scoping_with_assoc_production
